### ISSUE TITLE
Example in paper

### ISSUE THREAD

**Issue by malmza** [acaloiaro/topk-taupath#1]
Did you check your code for the example in the original paper?

Thank you.

**Comment by acaloiaro** [comment]
Hi @malmza I'm still in the process of validating this with some of the early TKTP code. I do recall making a change or two that will result in this implementation producing slightly different tau paths than those generated by the implementation from the original paper. 

With that said, the tau paths resulting from applying this fastBCS implementation should satisfy the monotonically decreasing property of the TKTP algorithm. 

However, I _am_ still in the process of re-familiarizing myself with this code so that I can use it as the basis for validating the forthcoming R and Java _FastBCS2_ implementation(s). 

I am fairly satisfied that it is correct, but I'm not yet 100% satisfied.

**Comment by acaloiaro** [comment]
Hi @malmza, I've provided more context in https://github.com/acaloiaro/topk-taupath/issues/2. I'm going to go ahead and close this issue for now. Cheers.

**Comment by malmza** [comment]
Thank you very much! Much Appreciate.
